jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      -  name: ChatGPT Reviewer
        uses: feiskyer/ChatGPT-Reviewer@v0.6

        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        env:
          TOKAN: ${{ secrets.TOKAN }}
        run: |
          npm run build
          git add dist/
          git commit -m "Update build artifacts"
          git push origin HEAD
